name: Node CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CI: true

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    services:
      postgres:
        image: postgres:10.11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - "0.0.0.0:5432:5432"
        # needed because the postgres container does not provide a healthcheck
        options:
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install pg_dump
        run: sudo apt-get install postgresql-client-10
      - name: yarn, lint, build and test
        # TODO: at a certain point we should remove --ignore-engines (when NES.css supports node 12)
        run: |
          cp .env.ci .env
          yarn --frozen-lockfile --ignore-engines
          CONFIRM_DROP=1 yarn setup
          yarn build
          yarn lint
          yarn test
          yarn depcheck
